FROM python:3.7
WORKDIR /code
ENV PYTHONUNBUFFERED=1
COPY wait.sh /wait.sh
RUN chmod +x /wait.sh
COPY requirements.txt /tmp/
RUN pip install -r /tmp/requirements.txt
ADD ./ /code
CMD /wait.sh db 5432 \
  && cd cmpt470 \
  && chmod -R 777 media \
  && ls -lha \
  && cd .. \
  && python cmpt470/manage.py collectstatic --noinput \
  && python cmpt470/manage.py migrate \
  && python cmpt470/manage.py loaddata data2.json \
  && /usr/local/bin/uwsgi --ini /code/cmpt470/cmpt470/uwsgi.ini
