# Generated by Django 2.2.3 on 2019-07-18 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='summary',
        ),
    ]
