# Generated by Django 2.2.3 on 2019-07-18 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0003_auto_20190718_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='image_url',
            field=models.CharField(max_length=800),
        ),
    ]
