# Generated by Django 2.2.3 on 2019-07-18 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0005_auto_20190718_0557'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='slug',
            field=models.SlugField(default='send-help'),
            preserve_default=False,
        ),
    ]
