# Generated by Django 2.2.3 on 2019-07-24 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0007_auto_20190724_0704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='summary',
            field=models.CharField(max_length=4000),
        ),
    ]
