# Generated by Django 2.2.3 on 2019-07-24 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0008_auto_20190724_0721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='coat',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='dog',
            name='color',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='dog',
            name='lifespan',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
    ]
