# Generated by Django 2.2.3 on 2019-07-24 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0009_auto_20190724_0739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='height',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='dog',
            name='nicknames',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='dog',
            name='origin',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='dog',
            name='other_names',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='dog',
            name='weight',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
    ]
