# Generated by Django 2.2.3 on 2019-07-27 16:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('animals', '0012_auto_20190724_0747'),
    ]

    operations = [
        migrations.CreateModel(
            name='Has_Spotted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animals.Animal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='has_spotted',
            constraint=models.UniqueConstraint(fields=('user', 'animal'), name='each user can only spot an animal once'),
        ),
    ]
